name: Create Archive
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'latest.zip'
        path: '/*ie7/* /*fonts/* selection.json styles.min.css weoicons_icons.dart'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "latest.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
